insert into restaurants (rname, totalseats, cuisinetype) values ('Afterglow',60,'Vegetarian');
insert into restaurants (rname, totalseats, cuisinetype) values ('Al Forno (East Coast) Italian Restaurant',60,'Italian');
insert into restaurants (rname, totalseats, cuisinetype) values ('Bao Makers',30,'Bar');
insert into restaurants (rname, totalseats, cuisinetype) values ('Bar-Roque Grill',60,'French');
insert into restaurants (rname, totalseats, cuisinetype) values ('BB Hotpot',60,'Steamboat');
insert into restaurants (rname, totalseats, cuisinetype) values ('Cali @ Rochester',30,'American');
insert into restaurants (rname, totalseats, cuisinetype) values ('Casa Poncho @ Bukit Pasoh',30,'Mexican');
insert into restaurants (rname, totalseats, cuisinetype) values ('Catchfly',60,'American');
insert into restaurants (rname, totalseats, cuisinetype) values ('Casuarina Curry (MacPherson)',30,'Indian');
insert into restaurants (rname, totalseats, cuisinetype) values ('Casuarina Curry (Sixth Avenue)',30,'Indian');
insert into restaurants (rname, totalseats, cuisinetype) values ('Casuarina Curry (Upper Thomson)',30,'Indian');
insert into restaurants (rname, totalseats, cuisinetype) values ('GEM Bar',30,'Burgers');
insert into restaurants (rname, totalseats, cuisinetype) values ('Gin Khao (One Raffles Place)',30,'Thai');
insert into restaurants (rname, totalseats, cuisinetype) values ('HANS IM GLÜCK German Burgergrill (Boat Quay)',30,'German');
insert into restaurants (rname, totalseats, cuisinetype) values ('HANS IM GLÜCK German Burgergrill (Orchard)',30,'German');
insert into restaurants (rname, totalseats, cuisinetype) values ('Imperial Court',30,'Dim Sum');
insert into restaurants (rname, totalseats, cuisinetype) values ('JUMBO Seafood (East Coast Seafood Centre)',60,'Seafood');
insert into restaurants (rname, totalseats, cuisinetype) values ('JUMBO Seafood (ION Orchard)',60,'Seafood');
insert into restaurants (rname, totalseats, cuisinetype) values ('Kith Cafe (Ascott Orchard)',30,'Cafe');
insert into restaurants (rname, totalseats, cuisinetype) values ('Kith Cafe (Bukit Timah)',30,'Australian');
insert into restaurants (rname, totalseats, cuisinetype) values ('Kyuu by Shunsui',100,'Japanese');
insert into restaurants (rname, totalseats, cuisinetype) values ('La Pizzeria at Bridge and Beacon Bar',30,'Italian');
insert into restaurants (rname, totalseats, cuisinetype) values ('La Strada',100,'Italian');
