delete from cuisines;
delete from restaurants;

insert into cuisines (cuisinetype) values ('All-Day Breakfast');
insert into cuisines (cuisinetype) values ('American');
insert into cuisines (cuisinetype) values ('Australian');
insert into cuisines (cuisinetype) values ('Bar');
insert into cuisines (cuisinetype) values ('BBQ');
insert into cuisines (cuisinetype) values ('British');
insert into cuisines (cuisinetype) values ('Buffet');
insert into cuisines (cuisinetype) values ('Burgers');
insert into cuisines (cuisinetype) values ('Cafe');
insert into cuisines (cuisinetype) values ('Cajun ');
insert into cuisines (cuisinetype) values ('Caribbean');
insert into cuisines (cuisinetype) values ('Chinese');
insert into cuisines (cuisinetype) values ('Cuban');
insert into cuisines (cuisinetype) values ('Dim Sum');
insert into cuisines (cuisinetype) values ('French');
insert into cuisines (cuisinetype) values ('Fusion');
insert into cuisines (cuisinetype) values ('German');
insert into cuisines (cuisinetype) values ('Greek');
insert into cuisines (cuisinetype) values ('Halal Certified');
insert into cuisines (cuisinetype) values ('Indian');
insert into cuisines (cuisinetype) values ('Indonesian');
insert into cuisines (cuisinetype) values ('International');
insert into cuisines (cuisinetype) values ('Italian');
insert into cuisines (cuisinetype) values ('Japanese');
insert into cuisines (cuisinetype) values ('Korean');
insert into cuisines (cuisinetype) values ('Local');
insert into cuisines (cuisinetype) values ('Malaysian');
insert into cuisines (cuisinetype) values ('Mexican');
insert into cuisines (cuisinetype) values ('Middle Eastern');
insert into cuisines (cuisinetype) values ('Modern Asian ');
insert into cuisines (cuisinetype) values ('Modern European');
insert into cuisines (cuisinetype) values ('Peranakan');
insert into cuisines (cuisinetype) values ('Pizza');
insert into cuisines (cuisinetype) values ('Portuguese');
insert into cuisines (cuisinetype) values ('Russian');
insert into cuisines (cuisinetype) values ('Seafood');
insert into cuisines (cuisinetype) values ('South American');
insert into cuisines (cuisinetype) values ('Southeast Asian');
insert into cuisines (cuisinetype) values ('Spanish');
insert into cuisines (cuisinetype) values ('Steakhouse');
insert into cuisines (cuisinetype) values ('Steamboat');
insert into cuisines (cuisinetype) values ('Swedish');
insert into cuisines (cuisinetype) values ('Thai');
insert into cuisines (cuisinetype) values ('Vegetarian');
insert into cuisines (cuisinetype) values ('Vegetarian Friendly');
insert into cuisines (cuisinetype) values ('Vietnamese');
insert into cuisines (cuisinetype) values ('Zi Char');

insert into restaurants (rname, totalseats, cuisinetype) values ('Afterglow',60,'Vegetarian');
insert into restaurants (rname, totalseats, cuisinetype) values ('Al Forno (East Coast) Italian Restaurant',60,'Italian');
insert into restaurants (rname, totalseats, cuisinetype) values ('Bao Makers',30,'Bar');
insert into restaurants (rname, totalseats, cuisinetype) values ('Bar-Roque Grill',60,'French');
insert into restaurants (rname, totalseats, cuisinetype) values ('BB Hotpot',60,'Steamboat');
insert into restaurants (rname, totalseats, cuisinetype) values ('Cali @ Rochester',30,'American');
insert into restaurants (rname, totalseats, cuisinetype) values ('Casa Poncho @ Bukit Pasoh',30,'Mexican');
insert into restaurants (rname, totalseats, cuisinetype) values ('Catchfly',60,'American');
insert into restaurants (rname, totalseats, cuisinetype) values ('Casuarina Curry (MacPherson)',30,'Indian');
insert into restaurants (rname, totalseats, cuisinetype) values ('Casuarina Curry (Sixth Avenue)',30,'Indian');
insert into restaurants (rname, totalseats, cuisinetype) values ('Casuarina Curry (Upper Thomson)',30,'Indian');
insert into restaurants (rname, totalseats, cuisinetype) values ('GEM Bar',30,'Burgers');
insert into restaurants (rname, totalseats, cuisinetype) values ('Gin Khao (One Raffles Place)',30,'Thai');
insert into restaurants (rname, totalseats, cuisinetype) values ('HANS IM GL�CK German Burgergrill (Boat Quay)',30,'German');
insert into restaurants (rname, totalseats, cuisinetype) values ('HANS IM GL�CK German Burgergrill (Orchard)',30,'German');
insert into restaurants (rname, totalseats, cuisinetype) values ('Imperial Court',30,'Dim Sum');
insert into restaurants (rname, totalseats, cuisinetype) values ('JUMBO Seafood (East Coast Seafood Centre)',60,'Seafood');
insert into restaurants (rname, totalseats, cuisinetype) values ('JUMBO Seafood (ION Orchard)',60,'Seafood');
insert into restaurants (rname, totalseats, cuisinetype) values ('Kith Cafe (Ascott Orchard)',30,'Cafe');
insert into restaurants (rname, totalseats, cuisinetype) values ('Kith Cafe (Bukit Timah)',30,'Australian');
insert into restaurants (rname, totalseats, cuisinetype) values ('Kyuu by Shunsui',100,'Japanese');
insert into restaurants (rname, totalseats, cuisinetype) values ('La Pizzeria at Bridge and Beacon Bar',30,'Italian');
insert into restaurants (rname, totalseats, cuisinetype) values ('La Strada',100,'Italian');
