insert into cuisines (cuisinetype) values ('All-Day Breakfast');
insert into cuisines (cuisinetype) values ('American');
insert into cuisines (cuisinetype) values ('Australian');
insert into cuisines (cuisinetype) values ('Bar');
insert into cuisines (cuisinetype) values ('BBQ');
insert into cuisines (cuisinetype) values ('British');
insert into cuisines (cuisinetype) values ('Buffet');
insert into cuisines (cuisinetype) values ('Burgers');
insert into cuisines (cuisinetype) values ('Cafe');
insert into cuisines (cuisinetype) values ('Cajun ');
insert into cuisines (cuisinetype) values ('Caribbean');
insert into cuisines (cuisinetype) values ('Chinese');
insert into cuisines (cuisinetype) values ('Cuban');
insert into cuisines (cuisinetype) values ('Dim Sum');
insert into cuisines (cuisinetype) values ('French');
insert into cuisines (cuisinetype) values ('Fusion');
insert into cuisines (cuisinetype) values ('German');
insert into cuisines (cuisinetype) values ('Greek');
insert into cuisines (cuisinetype) values ('Halal Certified');
insert into cuisines (cuisinetype) values ('Indian');
insert into cuisines (cuisinetype) values ('Indonesian');
insert into cuisines (cuisinetype) values ('International');
insert into cuisines (cuisinetype) values ('Italian');
insert into cuisines (cuisinetype) values ('Japanese');
insert into cuisines (cuisinetype) values ('Korean');
insert into cuisines (cuisinetype) values ('Local');
insert into cuisines (cuisinetype) values ('Malaysian');
insert into cuisines (cuisinetype) values ('Mexican');
insert into cuisines (cuisinetype) values ('Middle Eastern');
insert into cuisines (cuisinetype) values ('Modern Asian ');
insert into cuisines (cuisinetype) values ('Modern European');
insert into cuisines (cuisinetype) values ('Peranakan');
insert into cuisines (cuisinetype) values ('Pizza');
insert into cuisines (cuisinetype) values ('Portuguese');
insert into cuisines (cuisinetype) values ('Russian');
insert into cuisines (cuisinetype) values ('Seafood');
insert into cuisines (cuisinetype) values ('South American');
insert into cuisines (cuisinetype) values ('Southeast Asian');
insert into cuisines (cuisinetype) values ('Spanish');
insert into cuisines (cuisinetype) values ('Steakhouse');
insert into cuisines (cuisinetype) values ('Steamboat');
insert into cuisines (cuisinetype) values ('Swedish');
insert into cuisines (cuisinetype) values ('Thai');
insert into cuisines (cuisinetype) values ('Vegetarian');
insert into cuisines (cuisinetype) values ('Vegetarian Friendly');
insert into cuisines (cuisinetype) values ('Vietnamese');
insert into cuisines (cuisinetype) values ('Zi Char');
